### PR TITLE
Umpire

### PR DESCRIPTION
**Pull request by liruipeng**
This PR adds umpire options.

### CODE REVIEW

**Review by ulrikeyang — APPROVED** [review]
This looks good to me. I assume you tested this? Thanks

**Comment by liruipeng** [comment]
> This looks good to me. I assume you tested this? Thanks

Tested on lassen, which seemed fine.

**Comment by liruipeng** [comment]
@daboehme Does this look OK to you? Thanks

**Comment by daboehme** [comment]
Hi @liruipeng , thanks for getting this in so quickly! 
Did you try it with Umpire enabled? Looks like the Makefile doesn't set `-DHYPRE_USING_UMPIRE` anywhere.
Would be good to also get an Umpire option in the CMakeLists.txt but I can do that myself if needed. Can't say too much about the Hypre-specific things.

**Comment by liruipeng** [comment]
> Hi @liruipeng , thanks for getting this in so quickly! Did you try it with Umpire enabled? Looks like the Makefile doesn't set `-DHYPRE_USING_UMPIRE` anywhere. Would be good to also get an Umpire option in the CMakeLists.txt but I can do that myself if needed. Can't say too much about the Hypre-specific things.

Yes, I tried it. `HYPRE_USING_UMPIRE` is defined in hypre's header.

**Comment by daboehme** [comment]
> Yes, I tried it. `HYPRE_USING_UMPIRE` is defined in hypre's header with it is configure with `--with-umpire`.

Oh, I see. In that case looks good to me! Feel free to merge it, I can expand the CMake build script later.

**Pull request merged**
